### PR TITLE
Add in CLS support for modules that don't have it.

### PR DESCRIPTION
**Pull request by DanStaal**
Adding Connected Living Spaces support for the Flatbed, Hub, VTOL, and both Wheelbay modules.

Signed-off-by: Daniel T. Staal <DStaal@usa.net>

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
FYI, RoverDude prefers pull-requests be made to the "DEVELOP" branch.

**Comment by DanStaal** [comment]
Sorry - Coding at 1am, and I never even thought to look for different branches.  Should I re-do?

**Comment by Kerbas-ad-astra** [comment]
I would -- I've seen him close PRs to master, and have never seen him accept one.

**Comment by DanStaal** [comment]
Actually, it looks like the needed changes are already applied in dev.  So closing as resolved.  ;)

**Pull request closed without merging**
